In [11]:
import numpy as np

##CREATING 1-D ARRAY
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
##CREATING A 2-D ARRAY
arr1.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [8]:
##CREATING A 2-D ARRAY
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
##Arrange 0-100 with a gap of 5
np.arange(0,100,5)

##Create a matrix of size 3x4 with all values 1
np.ones((3,4))

##Create a matrix of size 4x5 with all values 0
np.zeros((4,4))

##Identity matrix
# np.eye(3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr4 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr4)
print(arr4.shape)
print(arr4.ndim)
print(arr4.size)
print(arr4.dtype)
print(arr4.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8
int64
8


In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition:",arr1+arr2)
print("Substraction:",arr2-arr1)
print("Multiplication:",arr1*arr2)
print("Divisional:",arr2/arr1)

Addition: [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Divisional: [10. 10. 10. 10. 10.]


In [36]:
##Universal function
arr = np.array([2,3,4,5,6])

##square root
print(f"Square root: {np.sqrt(arr)}")

##Exponential
print(f"Exponential: {np.exp(arr)}")

##Sine
print(f"Sine function: {np.sin(arr)}")

##Natural log
print(f"Natural log: {np.log(arr)}")

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine function: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [79]:
import numpy as np
arr=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

# print(arr[0])
# print(arr[1])
# print(arr[2])

# print("\n")
print(arr[2:])

# result_slicing = [row[2:4] for row in arr[0:2]]
# print(result_slicing)


[[11, 12, 13, 14, 15]]


In [74]:
import numpy as np
arr=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

arr[0][0] = 100
print(arr)



[[100, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [ ]:
import numpy as np

np_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])


np_arr[1:3, 3:5] = 100 

print(np_arr)

[[  1   2   3   4   5]
 [  6   7   8 100 100]
 [ 11  12  13 100 100]]


In [80]:
data = np.array([1,2,3,4,5])

##calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean)/std_dev
print("Normalised data: ", normalized_data)


Normalised data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [84]:
##Logical Operation

data = np.array([1,2,3,4,5,6,7,8])

print(data[data>5])
print(data[(data>=5) & (data<=8)])

[6 7 8]
[5 6 7 8]
