### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [38]:
import numpy as np
arr = np.random.randint(1,21,size=(5,5))

##replacing 3rd column with zero
arr[:, 4] = 1

print(arr)


[[12 15 11 17  1]
 [10 15 18  7  1]
 [11 19  7 10  1]
 [ 9 18 13  3  1]
 [ 4  8 18 12  1]]


In [41]:
arr2 = np.arange(1,17,1).reshape(4,4)

print(arr2)

print("\n Changed array \n")

np.fill_diagonal(arr2,0)
print(arr2)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Changed array 

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr3 = np.arange(1,37,1).reshape(6,6)
print(arr[2:5,1:4])


[[19  7 10]
 [18 13  3]
 [ 8 18 12]]


In [52]:
arr4 = np.random.randint(1,25,size=(5,5))
print(arr4)

print("\n Border elements \n")

border_element = np.concatenate((arr4[0,:],arr4[1:-1,-1],arr4[-1,:],arr4[:,0]))
print(border_element)


[[ 3 10 13  6 19]
 [12  3  8  3 12]
 [18 17 22 11 22]
 [10 14  5 18  2]
 [16  9 15  7  3]]

 Border elements 

[ 3 10 13  6 19 12 22  2 16  9 15  7  3  3 12 18 10 16]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [55]:
arr_51 = np.random.randint(1,25,size=(3,4))
arr_52 = np.random.randint(1,25,size=(3,4))

print("\n Addition \n")
print(arr_51+arr_52)
print("\n Subtraction \n")
print(arr_51-arr_52)
print("\n Multiplication \n")
print(arr_51*arr_52)
print("\n Division \n")
print(arr_51/arr_52)






 Addition 

[[33 26 33 23]
 [27 25 34 15]
 [27 41 29 32]]

 Subtraction 

[[ -9 -14 -13   1]
 [-21  13  -6  -9]
 [ 19   3   3  10]]

 Multiplication 

[[252 120 230 132]
 [ 72 114 280  36]
 [ 92 418 208 231]]

 Division 

[[0.57142857 0.3        0.43478261 1.09090909]
 [0.125      3.16666667 0.7        0.25      ]
 [5.75       1.15789474 1.23076923 1.90909091]]


In [61]:
arr6 = np.random.randint(1,25,size=(4,4))
print(arr6)
rows, columns = arr6.shape
print("\nSum of Rows\n")
for i in range(rows):
    sum = 0
    for j in range(columns):
        sum += arr6[i,j]
    print(f"{i}th row sum = {sum}")

print("\nSum of Columns\n")
for i in range(columns):
    sum = 0
    for j in range(rows):
        sum += arr6[j,i]
    print(f"{i}th col sum = {sum}")

# Compute the row-wise and column-wise sum
row_sum = np.sum(arr6, axis=1)
column_sum = np.sum(arr6, axis=0)

print("\nRow-wise sum:")
print(row_sum)
print("\nColumn-wise sum:")
print(column_sum)

    



[[ 8 11 17  7]
 [14 12 19 21]
 [19 21  4  5]
 [21 23 16  1]]

Sum of Rows

0th row sum = 43
1th row sum = 66
2th row sum = 49
3th row sum = 61

Sum of Columns

0th col sum = 62
1th col sum = 67
2th col sum = 56
3th col sum = 34

Row-wise sum:
[43 66 49 61]

Column-wise sum:
[62 67 56 34]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [66]:
arr7 = np.random.randint(1,100,size=(5,5))

print(f"Mean of array = {np.mean(arr7)}\n")
print(f"Standard deviation = {np.std(arr7)}\n")
print(f"Variance = {np.var(arr7)}\n")

normalised_Array = (arr7-np.mean(arr7))/(np.std(arr7))
print(f"Normalised Array : \n{normalised_Array}")

Mean of array = 48.28

Standard deviation = 26.958516279647142

Variance = 726.7616

Normalised Array : 
[[ 1.13952859  0.24927188 -1.01192513  1.47337485  0.10089576]
 [-0.04748036 -1.49414751 -1.64252363 -0.71517289  1.69593903]
 [-1.6054296  -0.86354901 -0.27004454  0.47183606 -0.41842065]
 [ 0.54602412 -0.30713856  0.06380173 -0.30713856  1.36209277]
 [ 0.73149426  0.06380173  1.21371665  1.17662262 -1.6054296 ]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [74]:
arr8 = np.random.randint(1,100,size=(3,3))
arr9 = np.random.randint(1,9,size=(3,))
print(f"Original 2d array: \n{arr8}\n")
print(f"1d array : \n{arr9}\n")

resulted_array = arr8 + arr9

print(f"Manipulated added 2d array: \n{resulted_array}\n")

subtracted_array = arr8 - arr9

print(f"Manipulated subtracted 2d array: \n{subtracted_array}")



Original 2d array: 
[[94 88 75]
 [26 61 92]
 [ 8 79  7]]

1d array : 
[5 1 6]

Manipulated added 2d array: 
[[99 89 81]
 [31 62 98]
 [13 80 13]]

Manipulated subtracted 2d array: 
[[89 87 69]
 [21 60 86]
 [ 3 78  1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [81]:
import numpy as np
from numpy import linalg as la
arr10 = np.random.randint(1,100,size=(3,3))
print(arr10)

determinant = la.det(arr10)
print(f"\nDeterminant = {determinant}\n")

inverse = la.inv(arr10)
print(f"\nInverse = {inverse}\n")

eigen_val, eigen_vector = la.eig(arr10)
print(f"\nEigen Value = {eigen_val.round(4)}\n")

[[97 86 63]
 [15 86 35]
 [18 43 70]]

Determinant = 344946.00000000035


Inverse = [[ 0.01308901 -0.0095986  -0.0069808 ]
 [-0.00121758  0.01639677 -0.00710256]
 [-0.0026178  -0.00760409  0.02044378]]


Eigen Value = [157.6103  56.9791  38.4106]

